Add missing plugin TypoScript
TYPO3-Documentation/TYPO3CMS-Exceptions pull request #153
Opened 2024-05-31 10:18 UTC by franzholz

2024-05-31 12:04 UTC, linawolf commented on Documentation/Exceptions/1540246570.rst
> +      controller.action = USER_INT
You should state which TYPO3 version you are talking about. Starting with TYPO3 12 there is EXTBASEPLUGIN https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/ContentObjects/Extbaseplugin/Index.html...

2024-05-31 13:20 UTC, froemken commented on Documentation/Exceptions/1540246570.rst
> +If your extension is not activated, then you need to activate it.
This is only valid for Standalone instances

2024-05-31 14:06 UTC, franzholz commented on Documentation/Exceptions/1540246570.rst
> +      controller.action = USER_INT
It is for a general plugin.

2024-05-31 14:07 UTC, franzholz commented on Documentation/Exceptions/1540246570.rst
> +If your extension is not activated, then you need to activate it.
What is a standalone instance?

2024-05-31 14:18 UTC, franzholz commented on Documentation/Exceptions/1540246570.rst
> +If your extension is not activated, then you need to activate it.
This is called [Legacy Installation](https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/LegacyInstallation.html)

2024-05-31 14:19 UTC, franzholz commented on Documentation/Exceptions/1540246570.rst
> +If your extension is not activated, then you need to activate it.
No, this error does not depend on TYPO3, but only on the extension.

2024-06-15 05:46 UTC, linawolf commented on Documentation/Exceptions/1540246570.rst
> +      controller.action = USER_INT
```suggestion
      controller.action = EXTBASEPLUGIN
```

2024-06-15 05:47 UTC, linawolf commented on Documentation/Exceptions/1540246570.rst
> +Always add the TypoScript for the tt_content list rendering.
the code below does not add TypoScript?

2024-06-15 05:47 UTC, linawolf requested changes
Please correct the code example

2024-06-15 05:49 UTC, linawolf commented on Documentation/Exceptions/1540246570.rst
> +If your extension is a general plugin and is not activated, then you need to activate it.
```suggestion
If your extension is a general plugin, check if it is properly installed (and activated for legacy installations)
and the required TypoScript included.
```

2024-06-15 09:54 UTC, franzholz commented on Documentation/Exceptions/1540246570.rst
> +Always add the TypoScript for the tt_content list rendering.
addPlugin modifies $GLOBALS['TCA']['tt_content'] only. 

Only ExtensionManagementUtility::addPItoST43 does it.
Or simply use the code below.  I just mention one solution.

2024-07-13 09:50 UTC, linawolf approved these changes

2024-07-13 09:51 UTC, linawolf commented on Documentation/Exceptions/1540246570.rst
> +Always add the TypoScript for the tt_content list rendering.
I will make a follow up

2024-07-13 09:51 UTC, merged