Link to talk.typo3.org instead of Slack in Exception note
TYPO3-Documentation/TYPO3CMS-Exceptions pull request #156
Opened 2024-06-13 15:27 UTC by pixeldesu

This adjusts the part of the exception troubleshooting note to now say:

> [...]
>
> General TYPO3 troubleshooting tips can be found in the section "Troubleshooting" of the menu. You can also ask questions and receive support in the ["TYPO3 Questions" category on talk.typo3.org](https://talk.typo3.org/c/typo3-questions/).
>
> [...]

This decision was made by @mabolek, since we want to get people to post their questions on https://talk.typo3.org primarily, so they are publicly searchable and indexable. This leads to less repeatedly asked questions, as happening in Slack (or other places that rely on real-time communications).

2024-06-13 15:47 UTC, garvinhicking commented
(Garvin speaking, not a capacity as a Documentation team member) I'm a bit reluctant to strike slack from here... talk.typo3.org is a bit of an empty place right now, and newbies might not get feedback there and then believe TYPO3 doesn't have a supportive community (which it has on slack). I know it's a chicken/egg problem, but we would need to provide quick and helpful feedback when someone has a problem, and that's often real-time like slack.

So, maybe we can try to foster one, without dropping the platform that currently has excellent support? I myself don't see me providing support on both platforms, and slack is much more integrated with me and other devs?

Having said that, I'm not one to decide on this 😏

2024-06-13 15:48 UTC, garvinhicking commented
(About the side question - no, links in our php-based renderings have a central style which resets and italics, afaik)

2024-06-13 18:04 UTC, garvinhicking commented
I had an eye-opening chat with Andreas and can better understand the goals and setup for this. So, let's try new things. 😃

(Still wearing my private hat 🤠)

2024-06-14 10:43 UTC, mabolek requested changes

2024-06-14 10:43 UTC, mabolek commented on Documentation/If-you-encounter-this-exception.rst.txt
> +   `"TYPO3 Questions" category on talk.typo3.org <https://talk.typo3.org/c/typo3-questions/>`__.
Some improved English — and let's just remove the quotes entirely.

```suggestion
   *Troubleshooting* section in the menu. You can also ask questions and receive support in the
   `TYPO3 Questions category on talk.typo3.org <https://talk.typo3.org/c/typo3-questions/>`__.
```

2024-06-14 12:41 UTC, mabolek approved these changes

2024-06-15 05:32 UTC, linawolf approved these changes

2024-06-15 05:32 UTC, merged

2024-06-15 05:33 UTC, linawolf commented
If you want to discuss styling topics differently please open an issue on https://github.com/TYPO3-Documentation/render-guides/issues