give another example of wrong arguments syntax
TYPO3-Documentation/TYPO3CMS-Exceptions pull request #62
Opened 2022-03-31 10:50 UTC by franzholz

2022-03-31 17:19 UTC, brotkrueml commented on Documentation/Exceptions/1256475113.rst
> +The syntax of the arguments format has been applied wrongy.
Typo: wrongy => wrongly

2022-03-31 19:47 UTC, jonaseberle requested changes

2022-04-01 07:53 UTC, jonaseberle commented on Documentation/Exceptions/1256475113.rst
> +`Fluid array syntax <https://docs.typo3.org/m/typo3/guide-extbasefluid/main/en-us/Fluid/ThingsToKnow/Arrays.html>`.
I am sorry, my previous suggestion was missing the `__` at the end for external links:
```suggestion
`Fluid array syntax <https://docs.typo3.org/m/typo3/guide-extbasefluid/main/en-us/Fluid/ThingsToKnow/Arrays.html>`__.
```

2022-04-01 07:57 UTC, jonaseberle approved these changes

2022-04-01 08:43 UTC, mbrodala approved these changes

2022-04-01 08:43 UTC, merged