Update 1365799920.rst
TYPO3-Documentation/TYPO3CMS-Exceptions pull request #74
Opened 2022-08-14 10:25 UTC by linawolf

2022-08-14 10:34 UTC, brotkrueml requested changes

2022-08-14 10:34 UTC, brotkrueml commented on Documentation/Exceptions/1365799920.rst
> +The fully Quallified class name of the validator in the annotation was wrong
```suggestion
The fully-qualified class name of the validator in the annotation was wrong
```

2022-08-14 10:35 UTC, brotkrueml approved these changes

2022-08-15 08:38 UTC, tomwarwick approved these changes

2022-08-15 08:39 UTC, merged